using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MotionLibrary;

namespace Product
{
    public class ProductTeachPointSettings : Machine.TeachPointSettings
    {
        public Motion.MotorProfile InputTrayTableXAxisForwardLimitPosition = new Motor.MotorProfile { Index = 0, TeachPointName = "Input Tray Table X Axis Forward Limit Position", TeachPoint = 85200, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 101, Module = "Input Tray Table", Description = "Input Tray Table X Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputTrayTableXAxisReverseLimitPosition = new Motor.MotorProfile { Index = 1, TeachPointName = "Input Tray Table X Axis Reverse Limit Position", TeachPoint = -85200, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 101, Module = "Input Tray Table", Description = "Input Tray Table X Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputTrayTableXAxisAtInputTrayStackerLoadPosition = new Motor.MotorProfile { Index = 2, TeachPointName = "At Input Tray Table X Axis Stacker Load Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 101, Module = "Input Tray Table", Description = "At Input Tray Table X Axis Stacker Load Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableXAxisAtInputTrayStackerUnloadPosition = new Motor.MotorProfile { Index = 3, TeachPointName = "At Input Tray Table X Axis Stacker Unload Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 101, Module = "Input Tray Table", Description = "At Input Tray Table X Axis Stacker Unload Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableXAxisAtInputTrayTableCenterPosition = new Motor.MotorProfile { Index = 4, TeachPointName = "At Input Tray Table X Axis Table Center Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 101, Module = "Input Tray Table", Description = "At Input Tray Table X Axis Table Center Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableXAxisAtInputSideWallVisionDotGridPosition = new Motor.MotorProfile { Index = 5, TeachPointName = "At Input Tray Table X Axis Side Wall Vision Dot Grid Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 101, Module = "Input Tray Table", Description = "At Input Tray Table X Axis Side Wall Vision Dot Grid Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableXAxisAtInputBottomAndVisionDotGridPosition = new Motor.MotorProfile { Index = 6, TeachPointName = "At Input Tray Table X Axis Bottom And Vision Dot Grid Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 101, Module = "Input Tray Table", Description = "At Input Tray Table X Axis Bottom And Vision Dot Grid Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile InputTrayTableYAxisForwardLimitPosition = new Motor.MotorProfile { Index = 7, TeachPointName = "Input Tray Table Y Axis Forward Limit Position", TeachPoint = 94100, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 102, Module = "Input Tray Table", Description = "Input Tray Table Y Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputTrayTableYAxisReverseLimitPosition = new Motor.MotorProfile { Index = 8, TeachPointName = "Input Tray Table Y Axis Reverse Limit Position", TeachPoint = -126900, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 102, Module = "Input Tray Table", Description = "Input Tray Table Y Axis Reverse Limit Positio", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputTrayTableYAxisAtInputTrayStackerLoadPosition = new Motor.MotorProfile { Index = 9, TeachPointName = "At Input Tray Table Y Axis Stacker Load Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 102, Module = "Input Tray Table", Description = "At Input Tray Table Y Axis Stacker Load Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableYAxisAtInputTrayStackerUnloadPosition = new Motor.MotorProfile { Index = 10, TeachPointName = "At Input Tray Table Y Axis Stacker Unload Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 102, Module = "Input Tray Table", Description = "At Input Tray Table Y Axis Stacker Unload Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableYAxisAtInputTrayTableCenterPosition = new Motor.MotorProfile { Index = 11, TeachPointName = "At Input Tray Table Y Axis Center Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 102, Module = "Input Tray Table", Description = "At Input Tray Table Y Axis Center Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableYAxisAtInputBottomDotGridPosition = new Motor.MotorProfile { Index = 12, TeachPointName = "At Input Tray Table Y Axis Bottom Dot Gird Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 102, Module = "Input Tray Table", Description = "At Input Tray Table Y Axis Bottom Dot Gird Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableYAxisAtInputVisionCalibrationPosition = new Motor.MotorProfile { Index = 13, TeachPointName = "At Input Tray Table Y Axis  Vision Calibration Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 102, Module = "Input Tray Table", Description = "At Input Tray Table Y Axis  Vision Calibration Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile InputTrayTableZAxisForwardLimitPosition = new Motor.MotorProfile { Index = 14, TeachPointName = "Input Tray Table Z Axis Forward Limit Position", TeachPoint = 27300, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 103, Module = "Input Tray Table", Description = "Input Tray Table Z Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputTrayTableZAxisReverseLimitPosition = new Motor.MotorProfile { Index = 15, TeachPointName = "Input Tray Table Z Axis Reverse Limit Position", TeachPoint = -2500, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 103, Module = "Input Tray Table", Description = "Input Tray Table Z Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputTrayTableZAxisDownPosition = new Motor.MotorProfile { Index = 16, TeachPointName = "At Input Tray Table Z Axis Down Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 103, Module = "Input Tray Table", Description = "At Input Tray Table Z Axis Down Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableZAxisAtInputTrayStackerLoadingPosition = new Motor.MotorProfile { Index = 17, TeachPointName = "At Input Tray Table Z Axis Stacker Loading Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 103, Module = "Input Tray Table", Description = "At Input Tray Table Z Axis Stacker Loading Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableZAxisAtInputTrayStackerSingulationPosition = new Motor.MotorProfile { Index = 18, TeachPointName = "At Input Tray Table Z Axis Stacker Singulation Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 103, Module = "Input Tray Table", Description = "At Input Tray Table Z Axis Stacker Singulation Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile InputTrayTableZAxisAtInputTrayStackerUnloadingPosition = new Motor.MotorProfile { Index = 19, TeachPointName = "At Input Tray Table Z Axis Stacker Unloading Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 103, Module = "Input Tray Table", Description = "At Input Tray Table Z Axis Stacker Unloading Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile OutputTrayTableXAxisForwardLimitPosition = new Motor.MotorProfile { Index = 20, TeachPointName = "Output Tray Table X Axis Forward Limit Position", TeachPoint = 89100, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "Output Tray Table X Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile OutputTrayTableXAxisReverseLimitPosition = new Motor.MotorProfile { Index = 21, TeachPointName = "Output Tray Table X Axis Reverse Limit Position", TeachPoint = -131900, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "Output Tray Table X Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile OutputTrayTableXAxisAtOutputTrayStackerLoadPosition = new Motor.MotorProfile { Index = 22, TeachPointName = "At Output Tray Table X Axis Stacker Load Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "At Output Tray Table X Axis Stacker Load Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableXAxisAtOutputTrayStackerUnloadPosition = new Motor.MotorProfile { Index = 23, TeachPointName = "At Output Tray Table X Axis Stacker Unload Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "At Output Tray Table X Axis Stacker Unload Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableXAxisAtOutputTrayTableCenterPosition = new Motor.MotorProfile { Index = 24, TeachPointName = "At Output Tray Table X Axis Center Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "At Output Tray Table X Axis Center Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableXAxisAtRejectTrayCenterPosition = new Motor.MotorProfile { Index = 25, TeachPointName = "At Reject Tray Table X Axis Center Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "At Reject Tray Table X Axis Center Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableXAxisAtOutputTrayTableManualLoadUnloadPosition = new Motor.MotorProfile { Index = 26, TeachPointName = "At Output Tray Table X Axis Manual Load Unload Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "At Output Tray Table X Axis Manual Load Unload Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableXAxisAtOutputVisionCalibrationPosition = new Motor.MotorProfile { Index = 27, TeachPointName = "At Output Tray Table X Axis Vision Calibration Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 104, Module = "Output Tray Table", Description = "At Output Tray Table X Axis Vision Calibration Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile OutputTrayTableYAxisForwardLimitPosition = new Motor.MotorProfile { Index = 28, TeachPointName = "Output Tray Table Y Axis Forward Limit Position", TeachPoint = 130400, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "Output Tray Table Y Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile OutputTrayTableYAxisReverseLimitPosition = new Motor.MotorProfile { Index = 29, TeachPointName = "Output Tray Table Y Axis Reverse Limit Position", TeachPoint = -97600, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "Output Tray Table Y Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile OutputTrayTableYAxisAtOutputTrayStackerLoadPosition = new Motor.MotorProfile { Index = 30, TeachPointName = "At Output Tray Table Y Axis Stacker Load Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "At Output Tray Table Y Axis Stacker Load Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableYAxisAtOutputTrayStackerUnloadPosition = new Motor.MotorProfile { Index = 31, TeachPointName = "At Output Tray Table Y Axis Stacker Unload Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "At Output Tray Table Y Axis Stacker Unload Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableYAxisAtOutputTrayTableCenterPosition = new Motor.MotorProfile { Index = 32, TeachPointName = "At Output Tray Table Y Axis Center Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "At Output Tray Table Y Axis Center Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableYAxisAtRejectTrayCenterPosition = new Motor.MotorProfile { Index = 33, TeachPointName = "At Reject Tray Table Y Axis Center Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "At Reject Tray Table Y Axis Center Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableYAxisAtOutputTrayTableManualLoadUnloadPosition = new Motor.MotorProfile { Index = 34, TeachPointName = "At Output Tray Table Y Axis Manual Load Unload Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "At Output Tray Table Y Axis Manual Load Unload Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableYAxisAtOutputVisionCalibrationPosition = new Motor.MotorProfile { Index = 35, TeachPointName = "At Output Tray Table Y Axis Vision Calibration Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 105, Module = "Output Tray Table", Description = "At Output Tray Table Y Axis Vision Calibration Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile OutputTrayTableZAxisForwardLimitPosition = new Motor.MotorProfile { Index = 36, TeachPointName = "Output Tray Table Z Axis Forward Limit Position", TeachPoint = 28500, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 106, Module = "Output Tray Table", Description = "Output Tray Table Z Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile OutputTrayTableZAxisReverseLimitPosition = new Motor.MotorProfile { Index = 37, TeachPointName = "Output Tray Table Z Axis Reverse Limit Position", TeachPoint = -3270, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 106, Module = "Output Tray Table", Description = "Output Tray Table Z Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile OutputTrayTableZAxisDownPosition = new Motor.MotorProfile { Index = 38, TeachPointName = "At Output Tray Table Z Axis Down Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 106, Module = "Output Tray Table", Description = "At Output Tray Table Z Axis Down Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableZAxisAtOutputTrayStackerLoadingPosition = new Motor.MotorProfile { Index = 39, TeachPointName = "At Output Tray Table Z Axis Stacker Loading Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 106, Module = "Output Tray Table", Description = "At Output Tray Table Z Axis Stacker Loading Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableZAxisAtOutputTrayStackerSingulationPosition = new Motor.MotorProfile { Index = 40, TeachPointName = "At Output Tray Table Z Axis Stacker Singulation Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 106, Module = "Output Tray Table", Description = "At Output Tray Table Z Axis Stacker Singulation Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableZAxisAtOutputTrayStackerUnloadingPosition = new Motor.MotorProfile { Index = 41, TeachPointName = "At Output Tray Table Z Axis Stacker Unloading Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 106, Module = "Output Tray Table", Description = "At Output Tray Table Z Axis Stacker Unloading Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace1XAxisForwardLimitPosition = new Motor.MotorProfile { Index = 42, TeachPointName = "Pick And Place 1 X Axis Forward Limit Position", TeachPoint = 235000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 X Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1XAxisReverseLimitPosition = new Motor.MotorProfile { Index = 43, TeachPointName = "Pick And Place 1 X Axis Reverse Limit Position", TeachPoint = -236900, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 X Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1XAxisInputPosition = new Motor.MotorProfile { Index = 44, TeachPointName = "Pick And Place 1 X Axis At Input Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 X Axis At Input Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1XAxisAtS1AndBottomVisionPosition = new Motor.MotorProfile { Index = 45, TeachPointName = "Pick And Place 1 X Axis At S1 And Bottom Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 X Axis At S1 And Bottom Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1XAxisAtS2AndS3VisionPosition = new Motor.MotorProfile { Index = 46, TeachPointName = "Pick And Place 1 X Axis At S2 And S3 Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 X Axis At S2 And S3 Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1XAxisOutputPosition = new Motor.MotorProfile { Index = 47, TeachPointName = "Pick And Place 1 X Axis At Output Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 X Axis At Output Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1XAxisParkingPosition = new Motor.MotorProfile { Index = 48, TeachPointName = "Pick And Place 1 X Axis At Parking Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 X Axis At Parking Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace1YAxisForwardLimitPosition = new Motor.MotorProfile { Index = 49, TeachPointName = "Pick And Place 1 Y Axis Forward Limit Position", TeachPoint = 26700, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 108, Module = "Pick And Place 1", Description = "Pick And Place 1 Y Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1YAxisReverseLimitPosition = new Motor.MotorProfile { Index = 50, TeachPointName = "Pick And Place 1 Y Axis Reverse Limit Position", TeachPoint = -5300, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 108, Module = "Pick And Place 1", Description = "Pick And Place 1 Y Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1YAxisInputPosition = new Motor.MotorProfile { Index = 51, TeachPointName = "Pick And Place 1 Y Axis At Input Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 108, Module = "Pick And Place 1", Description = "Pick And Place 1 Y Axis At Input Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1YAxisAtS1AndBottomVisionPosition = new Motor.MotorProfile { Index = 52, TeachPointName = "Pick And Place 1 Y Axis At S1 And Bottom Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 108, Module = "Pick And Place 1", Description = "Pick And Place 1 Y Axis At S1 And Bottom Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1YAxisAtS2AndS3VisionPosition = new Motor.MotorProfile { Index = 53, TeachPointName = "Pick And Place 1 Y Axis At S2 And S3 Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 108, Module = "Pick And Place 1", Description = "Pick And Place 1 Y Axis At S2 And S3 Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1YAxisOutputPosition = new Motor.MotorProfile { Index = 54, TeachPointName = "Pick And Place 1 Y Axis At Output Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 108, Module = "Pick And Place 1", Description = "Pick And Place 1 Y Axis At Output Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1YAxisStandbyPosition = new Motor.MotorProfile { Index = 55, TeachPointName = "Pick And Place 1 Y Axis At Standby Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 108, Module = "Pick And Place 1", Description = "Pick And Place 1 Y Axis At Standby Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace1ZAxisForwardLimitPosition = new Motor.MotorProfile { Index = 56, TeachPointName = "Pick And Place 1 Z Axis Forward Limit Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1ZAxisReverseLimitPosition = new Motor.MotorProfile { Index = 57, TeachPointName = "Pick And Place 1 Z Axis Reverse Limit Position", TeachPoint = -29000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1ZAxisUpPosition = new Motor.MotorProfile { Index = 58, TeachPointName = "Pick And Place 1 Z Axis At Up Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Up Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisUpPosition1 = new Motor.MotorProfile { Index = 59, TeachPointName = "Pick And Place 1 Z Axis At Up Position 1", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Up Position 1", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisUpPosition2 = new Motor.MotorProfile { Index = 60, TeachPointName = "Pick And Place 1 Z Axis At Up Position 2", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Up Position 2", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisAtInputTrayTouchingPosition = new Motor.MotorProfile { Index = 61, TeachPointName = "Pick And Place 1 Z Axis At Input Tray Touching Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Input Tray Touching Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisAtInputTrayDownPosition = new Motor.MotorProfile { Index = 62, TeachPointName = "Pick And Place 1 Z Axis At Input Tray Down Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Input Tray Down Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisAtInputTraySoftlandingPosition = new Motor.MotorProfile { Index = 63, TeachPointName = "Pick And Place 1 Z Axis At Input Tray Softlanding Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Input Tray Softlanding Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisAtOutputTrayTouchingPosition = new Motor.MotorProfile { Index = 64, TeachPointName = "Pick And Place 1 Z Axis At Output Tray Touching Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Output Tray Touching Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisAtOutputTrayDownPosition = new Motor.MotorProfile { Index = 65, TeachPointName = "Pick And Place 1 Z Axis At Output Tray Down Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Output Tray Down Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisAtOutputTraySoftlandingPosition = new Motor.MotorProfile { Index = 66, TeachPointName = "Pick And Place 1 Z Axis At Output Tray Softlanding Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Output Tray Softlanding Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace1ZAxisAtVisionFocusPosition = new Motor.MotorProfile { Index = 67, TeachPointName = "Pick And Place 1 Z Axis At Vision Focus Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 109, Module = "Pick And Place 1", Description = "Pick And Place 1 Z Axis At Vision Focus Position", Remark = "", EnableTeaching = false, Visible = true };

        public Motion.MotorProfile PickAndPlace1ThetaAxisForwardLimitPosition = new Motor.MotorProfile { Index = 68, TeachPointName = "Pick And Place 1 Theta Axis Forward Limit Position", TeachPoint = 180000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Theta Axis", AxisNo = 110, Module = "Pick And Place 1", Description = "Pick And Place 1 Theta Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1ThetaAxisReverseLimitPosition = new Motor.MotorProfile { Index = 69, TeachPointName = "Pick And Place 1 Theta Axis Reverse Limit Position", TeachPoint = -180000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Theta Axis", AxisNo = 110, Module = "Pick And Place 1", Description = "Pick And Place 1 Theta Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace1ThetaAxisStandbyPosition = new Motor.MotorProfile { Index = 70, TeachPointName = "Pick And Place 1 Theta Axis At Standby Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Theta Axis", AxisNo = 110, Module = "Pick And Place 1", Description = "Pick And Place 1 Theta Axis At Standby Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace2XAxisForwardLimitPosition = new Motor.MotorProfile { Index = 71, TeachPointName = "Pick And Place 2 X Axis Forward Limit Position", TeachPoint = 136300, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 X Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2XAxisReverseLimitPosition = new Motor.MotorProfile { Index = 72, TeachPointName = "Pick And Place 2 X Axis Reverse Limit Position", TeachPoint = -335700, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 X Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2XAxisInputPosition = new Motor.MotorProfile { Index = 73, TeachPointName = "Pick And Place 2 X Axis At Input Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 X Axis At Input Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2XAxisAtS1AndBottomVisionPosition = new Motor.MotorProfile { Index = 74, TeachPointName = "Pick And Place 2 X Axis At S1 And Bottom Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 X Axis At S1 And Bottom Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2XAxisAtS2AndS3VisionPosition = new Motor.MotorProfile { Index = 75, TeachPointName = "Pick And Place 2 X Axis At S2 And S3 Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 X Axis At S2 And S3 Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2XAxisOutputPosition = new Motor.MotorProfile { Index = 76, TeachPointName = "Pick And Place 2 X Axis At Output Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 X Axis At Output Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2XAxisParkingPosition = new Motor.MotorProfile { Index = 77, TeachPointName = "Pick And Place 2 X Axis At Parking Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 X Axis At Parking Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace2YAxisForwardLimitPosition = new Motor.MotorProfile { Index = 78, TeachPointName = "Pick And Place 2 Y Axis Forward Limit Position", TeachPoint = 5300, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 112, Module = "Pick And Place 2", Description = "Pick And Place 2 Y Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2YAxisReverseLimitPosition = new Motor.MotorProfile { Index = 79, TeachPointName = "Pick And Place 2 Y Axis Reverse Limit Position", TeachPoint = -26700, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 112, Module = "Pick And Place 2", Description = "Pick And Place 2 Y Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2YAxisInputPosition = new Motor.MotorProfile { Index = 80, TeachPointName = "Pick And Place 2 Y Axis At Input Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 112, Module = "Pick And Place 2", Description = "Pick And Place 2 Y Axis At Input Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2YAxisAtS1AndBottomVisionPosition = new Motor.MotorProfile { Index = 81, TeachPointName = "Pick And Place 2 Y Axis At S1 And Bottom Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 112, Module = "Pick And Place 2", Description = "Pick And Place 2 Y Axis At S1 And Bottom Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2YAxisAtS2AndS3VisionPosition = new Motor.MotorProfile { Index = 82, TeachPointName = "Pick And Place 2 Y Axis At S2 And S3 Vision Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 112, Module = "Pick And Place 2", Description = "Pick And Place 2 Y Axis At S2 And S3 Vision Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2YAxisOutputPosition = new Motor.MotorProfile { Index = 83, TeachPointName = "Pick And Place 2 Y Axis At Output Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 112, Module = "Pick And Place 2", Description = "Pick And Place 2 Y Axis At Output Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2YAxisStandbyPosition = new Motor.MotorProfile { Index = 84, TeachPointName = "Pick And Place 2 Y Axis At Standby Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Y Axis", AxisNo = 112, Module = "Pick And Place 2", Description = "Pick And Place 2 Y Axis At Standby Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace2ZAxisForwardLimitPosition = new Motor.MotorProfile { Index = 85, TeachPointName = "Pick And Place 2 Z Axis Forward Limit Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2ZAxisReverseLimitPosition = new Motor.MotorProfile { Index = 86, TeachPointName = "Pick And Place 2 Z Axis Reverse Limit Position", TeachPoint = -29000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2ZAxisUpPosition = new Motor.MotorProfile { Index = 87, TeachPointName = "Pick And Place 2 Z Axis At Up Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Up Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisUpPosition1 = new Motor.MotorProfile { Index = 88, TeachPointName = "Pick And Place 2 Z Axis At Up Position 1", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Up Position 1", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisUpPosition2 = new Motor.MotorProfile { Index = 89, TeachPointName = "Pick And Place 2 Z Axis At Up Position 2", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Up Position 2", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisAtInputTrayTouchingPosition = new Motor.MotorProfile { Index = 90, TeachPointName = "Pick And Place 2 Z Axis At Input Tray Touching Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Input Tray Touching Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisAtInputTrayDownPosition = new Motor.MotorProfile { Index = 91, TeachPointName = "Pick And Place 2 Z Axis At Input Tray Down Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Input Tray Down Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisAtInputTraySoftlandingPosition = new Motor.MotorProfile { Index = 92, TeachPointName = "Pick And Place 2 Z Axis At Input Tray Softlanding Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Input Tray Softlanding Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisAtOutputTrayTouchingPosition = new Motor.MotorProfile { Index = 93, TeachPointName = "Pick And Place 2 Z Axis At Output Tray Touching Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Output Tray Touching Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisAtOutputTrayDownPosition = new Motor.MotorProfile { Index = 94, TeachPointName = "Pick And Place 2 Z Axis At Output Tray Down Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Output Tray Down Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisAtOutputTraySoftlandingPosition = new Motor.MotorProfile { Index = 95, TeachPointName = "Pick And Place 2 Z Axis At Output Tray Softlanding Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Output Tray Softlanding Position", Remark = "", EnableTeaching = false, Visible = true };
        public Motion.MotorProfile PickAndPlace2ZAxisAtVisionFocusPosition = new Motor.MotorProfile { Index = 96, TeachPointName = "Pick And Place 2 Z Axis At Vision Focus Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 113, Module = "Pick And Place 2", Description = "Pick And Place 2 Z Axis At Vision Focus Position", Remark = "", EnableTeaching = false, Visible = true };

        public Motion.MotorProfile PickAndPlace2ThetaAxisForwardLimitPosition = new Motor.MotorProfile { Index = 97, TeachPointName = "Pick And Place 2 Theta Axis Forward Limit Position", TeachPoint = 180000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Theta Axis", AxisNo = 114, Module = "Pick And Place 2", Description = "Pick And Place 2 Theta Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2ThetaAxisReverseLimitPosition = new Motor.MotorProfile { Index = 98, TeachPointName = "Pick And Place 2 Theta Axis Reverse Limit Position", TeachPoint = -180000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Theta Axis", AxisNo = 114, Module = "Pick And Place 2", Description = "Pick And Place 2 Theta Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile PickAndPlace2ThetaAxisStandbyPosition = new Motor.MotorProfile { Index = 99, TeachPointName = "Pick And Place 2 Theta Axis At Standby Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Theta Axis", AxisNo = 114, Module = "Pick And Place 2", Description = "Pick And Place 2 Theta Axis At Standby Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile InputVisionZAxisForwardLimitPosition = new Motor.MotorProfile { Index = 100, TeachPointName = "Input Vision Z Axis Forward Limit Position", TeachPoint = 7300, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Input Vision Z Axis", AxisNo = 115, Module = "Vision", Description = "Input Vision Z Axis Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputVisionZAxisReverseLimitPosition = new Motor.MotorProfile { Index = 101, TeachPointName = "Input Vision Z Axis Reverse Limit Position", TeachPoint = -33100, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Input Vision Z Axis", AxisNo = 115, Module = "Vision", Description = "Input Vision Z Axis Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile InputVisionZAxisAtInputVisionFocusPosition = new Motor.MotorProfile { Index = 102, TeachPointName = "At Input Vision Focus Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Input Vision Z Axis", AxisNo = 115, Module = "Vision", Description = "At Input Vision Focus Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile S2VisionForwardLimitPosition = new Motor.MotorProfile { Index = 103, TeachPointName = "S2 Vision Forward Limit Position", TeachPoint = 13000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S2 Vision Axis", AxisNo = 116, Module = "Vision", Description = "S2 Vision Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile S2VisionReverseLimitPosition = new Motor.MotorProfile { Index = 104, TeachPointName = "S2 Vision Reverse Limit Position", TeachPoint = -27700, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S2 Vision Axis", AxisNo = 116, Module = "Vision", Description = "S2 Vision Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile S2VisionFocusPosition = new Motor.MotorProfile { Index = 105, TeachPointName = "S2 Vision Focus Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S2 Vision Axis", AxisNo = 116, Module = "Vision", Description = "S2 Vision Focus Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile S1VisionForwardLimitPosition = new Motor.MotorProfile { Index = 106, TeachPointName = "S1 Vision Forward Limit Position", TeachPoint = 27700, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S1 Vision Axis", AxisNo = 117, Module = "Vision", Description = "S1 Vision Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile S1VisionReverseLimitPosition = new Motor.MotorProfile { Index = 107, TeachPointName = "S1 Vision Reverse Limit Position", TeachPoint = -13000, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S1 Vision Axis", AxisNo = 117, Module = "Vision", Description = "S1 Vision Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile S1VisionFocusPosition = new Motor.MotorProfile { Index = 108, TeachPointName = "S1 Vision Focus Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S1 Vision Axis", AxisNo = 117, Module = "Vision", Description = "Focus Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile S3VisionForwardLimitPosition = new Motor.MotorProfile { Index = 109, TeachPointName = "S3 Vision Forward Limit Position", TeachPoint = 13600, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S3 Vision Axis", AxisNo = 121, Module = "Vision", Description = "S3 Vision Forward Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile S3VisionReverseLimitPosition = new Motor.MotorProfile { Index = 110, TeachPointName = "S3 Vision Reverse Limit Position", TeachPoint = -22300, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S3 Vision Axis", AxisNo = 121, Module = "Vision", Description = "S3 Vision Reverse Limit Position", Remark = "", EnableTeaching = false, Visible = false };
        public Motion.MotorProfile S3VisionFocusPosition = new Motor.MotorProfile { Index = 111, TeachPointName = "S3 Vision Focus Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S3 Vision Axis", AxisNo = 121, Module = "Vision", Description = "S3 Vision Focus Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace1XAxisAwayOutputPosition = new Motor.MotorProfile { Index = 130, TeachPointName = "Pick And Place 1 Away Output Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 Away Output Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2XAxisAwayOutputPosition = new Motor.MotorProfile { Index = 131, TeachPointName = "Pick And Place 2 Away Output Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 Away Output Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile PickAndPlace1XAxisAwayInputPosition = new Motor.MotorProfile { Index = 132, TeachPointName = "Pick And Place 1 Away Input Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 107, Module = "Pick And Place 1", Description = "Pick And Place 1 Away Input Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile PickAndPlace2XAxisAwayInputPosition = new Motor.MotorProfile { Index = 133, TeachPointName = "Pick And Place 2 Away Input Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "X Axis", AxisNo = 111, Module = "Pick And Place 2", Description = "Pick And Place 2 Away Input Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile S1VisionRetractPosition = new Motor.MotorProfile { Index = 135, TeachPointName = "S1 Vision Retract Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "S1 Vision Axis", AxisNo = 117, Module = "Vision", Description = "S1 Vision Retract Position", Remark = "", EnableTeaching = true, Visible = true };

        public Motion.MotorProfile InputTrayTableZAxisAtInputTrayStackerSecondSingulationPosition = new Motor.MotorProfile { Index = 136, TeachPointName = "At Input Tray Table Z Axis Stacker Second Singulation Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 103, Module = "Input Tray Table", Description = "At Input Tray Table Z Axis Stacker Second Singulation Position", Remark = "", EnableTeaching = true, Visible = true };
        public Motion.MotorProfile OutputTrayTableZAxisAtOutputTrayStackerSecondSingulationPosition = new Motor.MotorProfile { Index = 137, TeachPointName = "At Output Tray Table Z Axis Stacker Second Singulation Position", TeachPoint = 0, ProfileName = "Normal", ProfileNo = 0, Speed = 1000, Acceleration = 1000, Deceleration = 1000, Unit = "um", Axis = "Z Axis", AxisNo = 106, Module = "Output Tray Table", Description = "At Output Tray Table Z Axis Stacker Second Singulation Position", Remark = "", EnableTeaching = true, Visible = true };


    }
}
